# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/

app = 'ds'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  BODY_SIZE_LIMIT = '20M'
  NODE_OPTIONS = '--max-old-space-size=2048'
  ENV_NAME = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 75

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/healthcheck'
    protocol = 'http'

[[mounts]]
  source = 'turso_data'
  destination = '/app/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
