name: 'Setup and install'
description: 'Common setup steps for Actions'

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      name: Read .nvmrc
      id: nvm

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}
        cache: 'pnpm'

    - shell: bash
      run: pnpm install --frozen-lockfile
