name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: Run Migrations
    runs-on: ubuntu-latest
    env:
      TURSO_DB_URL: ${{ secrets.TURSO_DB_URL }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/shared
      - name: Run database migrations
        run: pnpm db:migrate

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [migrate]
    concurrency: deploy-group
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Generate .env File
        run: |
          cat <<EOF > .env
          TURSO_DB_URL=${{ secrets.TURSO_DB_URL }}
          TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }}
          AUTH_COOKIE_VALUE=${{ secrets.AUTH_COOKIE_VALUE }}
          LOGIN_U=${{ secrets.LOGIN_U }}
          LOGIN_P=${{ secrets.LOGIN_P }}
          ACTIVITY_INGEST_TOKEN=${{ secrets.ACTIVITY_INGEST_TOKEN }}
          OMDB_API_KEY=${{ secrets.OMDB_API_KEY }}
          PLEX_WEBHOOK_TOKEN=${{ secrets.PLEX_WEBHOOK_TOKEN }}
          PLEX_ACCOUNT_NAME=${{ secrets.PLEX_ACCOUNT_NAME }}
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_R2_ACCESS_KEY=${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}
          CLOUDFLARE_R2_SECRET_KEY=${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
          CLOUDFLARE_R2_BUCKET_NAME=${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}
          ENV_NAME=production
          EOF
      - uses: ./.github/shared
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
